package com.sample.rules

rule "Ask brother age"
    salience -10
    when
        // Context: The user has specified the relation is "Brother".
        Answer(questionId == "relationMale", value == "Brother")
        not Question(id == "brotherAge")
    then
        Question q = new Question();
        q.setId("brotherAge");
        q.setText("Younger or older?");
        q.setOptions("Older|Younger");
        q.setAnswered(false);
        q.setMultiSelect(false);
        insert(q);
end

rule "Brother is Older"
    when
        $s : State(phase == "MALE_BROTHER")
        Answer(questionId == "brotherAge", value == "Older")
    then
        modify($s) { setPhase("MALE_BROTHER_OLDER") };
end

rule "Ask if older brother picked on you"
    salience -10
    when
        State(phase == "MALE_BROTHER_OLDER")
        not Question(id == "pickedOnYou")
    then
        Question q = new Question();
        q.setId("pickedOnYou");
        q.setText("So he probably picked on you when you were growing up?");
        q.setOptions("He was a master of the noogie|No, never!");
        q.setAnswered(false);
        q.setMultiSelect(false);
        insert(q);
end

rule "Older brother picked on you (Noogie)"
    when
        $s : State(phase == "MALE_BROTHER_OLDER")
        Answer(questionId == "pickedOnYou", value == "He was a master of the noogie")
    then
        insert(new Recommendation("Holiday 4-Pack", "Here’s what you do: Get him a Holiday 4-Pack, then get yourself a 10-Pack and passive-aggressively demonstrate your newfound superiority."));
end

rule "Older brother picked on you (No)"
    when
        State(phase == "MALE_BROTHER_OLDER")
        Answer(questionId == "pickedOnYou", value == "No, never!")
    then
        insert(new Recommendation("Holiday 4-Pack", "You have the best older brother ever! Get a pair of Holiday 4-Packs and enjoy some quality time with this great guy."));
end

rule "Brother is Younger"
    when
        $s : State(phase == "MALE_BROTHER")
        Answer(questionId == "brotherAge", value == "Younger")
    then
        modify($s) { setPhase("MALE_BROTHER_YOUNGER") };
end

rule "Ask if picked on younger brother"
    salience -10
    when
        State(phase == "MALE_BROTHER_YOUNGER")
        not Question(id == "pickedOnBrother")
    then
        Question q = new Question();
        q.setId("pickedOnBrother");
        q.setText("So you probably picked on him when you were growing up?");
        q.setOptions("Yeah, sure did|No, never!");
        q.setAnswered(false);
        q.setMultiSelect(false);
        insert(q);
end

rule "Picked on younger brother"
    when
        Answer(questionId == "relationMale", value == "Brother")
        Answer(questionId == "brotherAge", value == "Younger")
        Answer(questionId == "pickedOnBrother", value == "Yeah, sure did")
    then
        insert(new Recommendation("Holiday 4-Pack", "Show him how much you've grown and make amends for your adolescent bullying by getting him a Holiday 4-pack."));
end

rule "Did not pick on younger brother"
    when
        Answer(questionId == "relationMale", value == "Brother")
        Answer(questionId == "brotherAge", value == "Younger")
        Answer(questionId == "pickedOnBrother", value == "No, never!")
    then
        insert(new Recommendation("Holiday 4-Pack", "You are the best older brother ever! You have probably already bought him multiple Holiday 4- Packs."));
end
