package com.sample.rules

rule "Recommend for Father-in-law"
    when
        // Context: The user has specified the relation is "Father-in-law".
        Answer(questionId == "relationMale", value == "Father-in-law")
    then
        insert(new Recommendation("Holiday 4-Pack", "Face it, you’ll never be good enough for his daughter. Your best chance of redeeming yourself would be to get him a Holiday 4-Pack."));
end
