package com.sample.rules

rule "Ask relation (female)"
    salience 100
    when
        State(phase == "FEMALE")
        not Question(id == "relationFemale")
    then
        Question q = new Question();
        q.setId("relationFemale");
        q.setText("Let's face it, you are in trouble. Why are you buying her a gift?");
        q.setOptions("Wife|Girlfriend|Mom|Mother-in-law|Sister|Co-worker");
        q.setAnswered(false);
        insert(q);
end
