package com.sample.rules

declare Question
    id : String
    text : String
    options : String
    answered : boolean
    multiSelect : boolean
end

declare Answer
    questionId : String
    value : String
end

declare Recommendation
    gift : String
    reason : String
end

global javax.swing.JFrame frame;

rule "Ask gender"
    salience -10
    when
        // This is the first question, it fires when no other facts (Questions, Answers) exist.
        not (Question() or Answer())
    then
        Question q = new Question();
        q.setId("gender");
        q.setText("What is the gender of the person receiving your gift?");
        q.setOptions("Male|Female");
        q.setAnswered(false);
        q.setMultiSelect(false);
        insert(q);
end

rule "Ask relation (male)"
    salience -10
    when
        // This is the context-based approach. The rule fires based on a previous answer.
        Answer(questionId == "gender", value == "Male")
        not Question(id == "relationMale")
        not Answer(questionId == "relationMale")
    then
        Question q = new Question();
        q.setId("relationMale");
        q.setText("This is gonna be hard. Guys don't buy gifts for other guys. Why are you buying him a gift?");
        q.setOptions("Dad|Brother|Crazy Uncle Charlie|Co-worker|Father-in-law");
        q.setAnswered(false);
        q.setMultiSelect(false);
        insert(q);
end